#!/usr/bin/env python3
""" Factor numbers """
from sys import argv


def open_read_file(file_name):
    """read from file and add to array"""
    with open(file_name, "r", encoding="utf-8") as file:
        lines = file.readlines()
    number_to_factor = []
    for line in lines:
        # strip() is used to remove trailing newline characters
        number_to_factor.append(int(line.strip()))
    return number_to_factor


def find_and_times(n):
    """factor each n given"""
    for i in range(2, n):  # start from 2 because 1 is not a proper factor
        if n % i == 0:  # use modulus to check if i is a factor of n
            print("{}={}*{}".format(n, i, n // i))  # print the factors
            break  # break after finding the first pair of factors


def fac_list(ls):
    """factor each num in ls"""
    for i in ls:
        find_and_times(i)


if __name__ == "__main__":  # added this line to ensure the script doesn't run when imported
    if len(argv) == 2:
        fac_list(open_read_file(argv[1]))
