#!/usr/bin/env python3
""" Factor numbers into primes """
from sys import argv
import math


def open_read_file(file_name):
    """read from file and add to array"""
    with open(file_name, "r", encoding="utf-8") as file:
        lines = file.readlines()
    number_to_factor = []
    for line in lines:
        number_to_factor.append(int(line))
    return number_to_factor


def is_prime(n):
    """check if a number is prime"""
    if n <= 1:
        return False
    if n == 2:
        return True
    if n % 2 == 0:
        return False
    sqrt_n = math.isqrt(n)
    for i in range(3, sqrt_n + 1, 2):
        if n % i == 0:
            return False
    return True


def find_prime_factors(n):
    """factor each n given into two primes"""
    for i in range(2, math.isqrt(n) + 1):
        if n % i == 0:
            j = n // i
            if is_prime(i) and is_prime(j):
                print(f"{n}={i}*{j}")
                break


def fac_list(ls):
    """factor each num in ls"""
    for i in ls:
        find_prime_factors(i)


if len(argv) == 2:
    fac_list(open_read_file(argv[1]))
